label: Multimedia
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      fields:
        thumbnail__target_id:
          label: Miniatura
        name:
          label: 'Nombre del elemento multimedia'
        bundle:
          label: Tipo
        uid:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
            format_custom_false: 'No publicado'
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        name:
          expose:
            label: 'Nombre del elemento multimedia'
        bundle:
          expose:
            label: Tipo
        status:
          expose:
            label: Verdadero
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'No publicado'
        langcode:
          expose:
            label: Idioma
      title: Multimedia
  media_page_list:
    display_title: Multimedia
    display_options:
      menu:
        title: Multimedia
