ignored_config_entities:
  - amplitude.settings
  - tmgmt.translator.xtm
  - sendgrid_integration.settings
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_collections: {  }
