verbose: 1
types:
  content_moderation_state: {  }
  file: {  }
  group: {  }
  group_content: {  }
  media: {  }
  node:
    '*': '*'
  redirect: {  }
  search_api_task: {  }
  shortcut: {  }
  taxonomy_term: {  }
  user: {  }
  menu_link_content: {  }
  paragraph: {  }
  location: {  }
types_translation_lock: {  }
types_js_lock:
  - node
form_op_lock:
  content_moderation_state:
    mode: 0
    values: {  }
  file:
    mode: null
    values: {  }
  group:
    mode: 0
    values: {  }
  group_content:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  redirect:
    mode: 0
    values: {  }
  search_api_task:
    mode: null
    values: {  }
  shortcut:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
  location:
    mode: 0
    values: {  }
_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
